#!/usr/bin/env python3
"""Build the graph-compose-emoji resource set from googlefonts/noto-emoji + github/gemoji.

Copies every noto colour-emoji SVG into the module under a codepoint filename and
generates the shortcode index that EmojiLibrary resolves.

Sources (download first, e.g. into target/):
  * noto SVGs:  git clone --depth 1 --filter=blob:none --sparse \\
                  https://github.com/googlefonts/noto-emoji.git
                (cd noto-emoji && git sparse-checkout set svg)   -> svg/emoji_u<cps>.svg
  * gemoji db:  https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

Mapping rules:
  * filename: noto  emoji_u1f468_200d_1f4bb.svg  ->  1f468-200d-1f4bb.svg
  * a gemoji entry's `emoji` is lowered to its hex codepoints; the U+FE0F variation
    selector is dropped (noto omits it) before matching a glyph file. Each alias of a
    matched entry becomes  alias=codepoint  in emoji-index.properties.

Usage:
  python emoji/tools/build-emoji-set.py \\
      --noto target/noto-emoji/svg --gemoji target/gemoji.json \\
      --out emoji/src/main/resources/emoji
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

FE0F = "fe0f"
NOTO_RE = re.compile(r"^emoji_u([0-9a-fA-F_]+)\.svg$")


def noto_codepoints(filename: str):
    """'emoji_u1f468_200d_1f4bb.svg' -> ['1f468','200d','1f4bb'] (lowercased)."""
    m = NOTO_RE.match(filename)
    if not m:
        return None
    return [part.lower() for part in m.group(1).split("_") if part]


def emoji_codepoints(emoji: str):
    """A unicode emoji string -> its hex codepoints, with FE0F dropped (noto omits it)."""
    cps = [format(ord(ch), "x") for ch in emoji]
    return [cp for cp in cps if cp != FE0F]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--noto", required=True, help="noto-emoji svg/ directory")
    ap.add_argument("--gemoji", required=True, help="gemoji db/emoji.json")
    ap.add_argument("--out", required=True, help="emoji/ resources root (svg/ + index written here)")
    args = ap.parse_args()

    noto_dir = Path(args.noto)
    out_root = Path(args.out)
    svg_out = out_root / "svg"
    if svg_out.exists():
        shutil.rmtree(svg_out)
    svg_out.mkdir(parents=True, exist_ok=True)

    # 1) Copy every noto glyph under a codepoint filename; remember which keys exist.
    keys = set()
    glyphs = 0
    for src in sorted(noto_dir.glob("emoji_u*.svg")):
        cps = noto_codepoints(src.name)
        if not cps:
            continue
        key = "-".join(cps)
        shutil.copyfile(src, svg_out / f"{key}.svg")
        keys.add(key)
        glyphs += 1

    # 2) Build the shortcode index from gemoji, matching codepoints to copied glyphs.
    db = json.loads(Path(args.gemoji).read_text(encoding="utf-8"))
    index = {}
    unmatched = 0
    for entry in db:
        emoji = entry.get("emoji")
        aliases = entry.get("aliases") or []
        if not emoji or not aliases:
            continue
        key = "-".join(emoji_codepoints(emoji))
        if key not in keys:
            # try keeping FE0F as a fallback (a few glyphs are named with it)
            alt = "-".join(format(ord(ch), "x") for ch in emoji)
            if alt in keys:
                key = alt
            else:
                unmatched += 1
                continue
        for alias in aliases:
            index[alias.strip().lower()] = key

    # 3) Write the index, sorted for a stable diff.
    lines = ["# Generated by emoji/tools/build-emoji-set.py from googlefonts/noto-emoji + github/gemoji.",
             "# shortcode = lowercase-hex codepoint(s); glyph at emoji/svg/<codepoint>.svg",
             "# Regenerate, do not hand-edit."]
    for alias in sorted(index):
        lines.append(f"{alias}={index[alias]}")
    (out_root / "emoji-index.properties").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"glyphs copied : {glyphs}")
    print(f"shortcodes    : {len(index)}")
    print(f"gemoji unmatched (no noto glyph): {unmatched}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
