package com.demcha.components.containers.abstract_builders;

import com.demcha.core.PdfDocument;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;

/** Represents an empty box or container within a PDF document.
 *
 * <p>This abstract base class provides a common structure for components that might not render visible content themselves
 * but serve as a placeholder or a base for more complex layouts within a PDF document.
 * It is designed to be extended by concrete builder classes that define specific empty box behaviors or act as
 * foundational elements for other layout components.</p>
 *
 * <h3>Purpose:</h3>
 * <ul>
 *     <li>To provide a lightweight base class for components that primarily serve as structural elements or placeholders.</li>
 *     <li>To encapsulate the {@link PdfDocument} instance, making it available to subclasses for PDF manipulation.</li>
 *     <li>To facilitate the creation of a hierarchy of layout builders where some elements might not have direct visual output.</li>
 * </ul>
 *
 * <h3>Methods Covered:</h3>
 * <p>As an abstract class, {@code EmptyBox} itself does not provide public methods beyond those inherited from {@link EntityBuilderBase}
 * or implicitly generated by Lombok annotations (e.g., a getter for {@code document}). Subclasses are expected to implement
 * specific rendering or layout logic. The primary method to be covered by subclasses is typically related to
 * building or adding content to the {@link PdfDocument} instance.</p>
 */
@Getter
@RequiredArgsConstructor
@Accessors(fluent = true)
public abstract class EmptyBox<T> extends EntityBuilderBase<T> implements BuildEntity {
    protected final PdfDocument document;
}
