/**
 * GraphCompose showcase site — renders the category-driven gallery
 * from web/examples.json. Generated by ShowcaseSync from
 * examples/target/generated-pdfs/.
 *
 * Author-side workflow:
 *   1) Add a new example .java under examples/.../com/demcha/examples/
 *      following the category subfolder convention
 *      (templates/<group>, features/<group>, flagships).
 *   2) Wire the example into GenerateAllExamples.
 *   3) Add a metadata entry in ShowcaseMetadata.java.
 *   4) Run GenerateAllExamples then ShowcaseSync — the new card
 *      appears here automatically without any HTML edits.
 */
(function () {
  'use strict';

  const MANIFEST_URL = 'examples.json';
  // Where a visitor is sent when the catalogue cannot be shown.
  const SOURCE_URL = 'https://github.com/DemchaAV/GraphCompose/tree/main/examples/src/main/java/com/demcha/examples';
  const CONTENT = document.getElementById('showcase-content');
  const SEARCH = document.getElementById('showcase-search');
  const FILTERS = document.getElementById('showcase-filters');
  // The document viewer (gallery-viewer.js). Without it a card opens its PDF.
  const Gallery = window.GraphComposeGallery || null;
  const VIEWER_DIALOG = document.getElementById('gallery-viewer');

  // Hand-picked highlights — one strong tile from each category
  // shown at the top of #showcase so first-time visitors see the
  // most visually striking work immediately, instead of having to
  // scroll past 15 plain cover letters to find the cinematic
  // proposal or the canvas demo. An id that is not a card in
  // examples.json is skipped here without a sign, so
  // ShowcaseSiteGuardTest fails the build on one instead.
  const HIGHLIGHT_IDS = [
    'project-proposal-cinematic',
    'master-showcase',
    'invoice-cinematic',
    'cv-sidebar-portrait-v2',
    'business-report',
    'canvas-layer-showcase',
    'cv-monogram-sidebar-v2',
    'table-advanced'
  ];

  // category id -> short label shown as a badge on each tile.
  const CATEGORY_BADGE = {
    templates: 'Template',
    features: 'Feature',
    flagships: 'Flagship'
  };

  // The ATS statuses that earn the "ATS-friendly" chip on a CV card.
  // ShowcaseSync already writes whether a card has one; the status is
  // checked here as well, so a badge flag edited on its own shows nothing.
  const ATS_BADGE_STATUSES = new Set([
    'ATS_CERTIFIED',
    'ATS_COMPATIBLE_WITH_KNOWN_PARSER_LIMITATIONS'
  ]);
  const ATS_BADGE_CLAIM = 'Validated for text extraction, section recognition and reading order '
    + 'using multiple independent PDF resume parsers.';

  // Groups whose card grid is collapsed by default to "first 4
  // visible + Show all (N)" — protects the page from the 15-letter
  // cover letter wall while still letting users browse the full set.
  const COLLAPSE_GROUPS = new Set(['coverletter']);
  const COLLAPSED_VISIBLE = 4;

  let manifest = null;
  let activeCategory = 'all';
  let activeQuery = '';
  let catalogue = null;
  let viewer = null;

  fetch(MANIFEST_URL, { cache: 'no-cache' })
    .then(r => {
      if (!r.ok) throw new Error('Manifest fetch failed: ' + r.status);
      return r.json();
    })
    .then(data => {
      manifest = data;
      injectFullItemListJsonLd();
      startViewer();
      // An anchor in the address bar may name a category section, which does
      // not exist until its filter renders it. The page then opens at the
      // gallery, unless the browser is putting the reader back where they were.
      // A viewer address selects the filter of its own category and opens the viewer over
      // it, so closing lands on that part of the gallery. A browser without `<dialog>`
      // cannot show the viewer at all: there the reader gets that gallery rather than the
      // top of the page.
      const route = viewerRoute(location.hash);
      const categoryId = categoryForHash(route ? '#' + route.category + '-section' : location.hash);
      if (categoryId) setCategory(categoryId);
      render();
      if (route) {
        if (!openRoute(route, 'none', null) && !isRestoringScroll()) scrollToGallery(true);
      } else if (categoryId && !isRestoringScroll()) {
        scrollToGallery(true);
      }
    })
    .catch(err => {
      CONTENT.innerHTML =
        '<p class="showcase-error">The example catalogue could not be loaded. ' +
        'Refresh the page, or browse the examples on ' +
        '<a href="' + SOURCE_URL + '">GitHub</a>.</p>';
      console.error(err);
    });

  // After the manifest loads, append a full ItemList JSON-LD block
  // listing every example. The static head ships only 7 entries
  // (so crawlers without JS still see structured data); this
  // upgrade gives Googlebot the complete catalogue once the
  // page renders.
  function injectFullItemListJsonLd() {
    if (!manifest || !document.head) return;
    const baseUrl = 'https://demchaav.github.io/GraphCompose/';
    const items = [];
    let position = 1;
    for (const category of manifest.categories || []) {
      for (const group of category.groups || []) {
        for (const ex of group.examples || []) {
          if (!ex || !ex.id) continue;
          const item = {
            '@type': 'ListItem',
            position: position++,
            name: ex.title || ex.id,
            url: ex.pdf ? baseUrl + ex.pdf : baseUrl
          };
          if (ex.description) item.description = ex.description;
          if (ex.screenshot) item.image = baseUrl + ex.screenshot;
          items.push(item);
        }
      }
    }
    const data = {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'GraphCompose showcase examples',
      description: 'Full searchable catalogue of GraphCompose example PDFs (templates, features, flagships).',
      numberOfItems: items.length,
      itemListElement: items
    };
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.dataset.injected = 'examples-itemlist';
    script.textContent = JSON.stringify(data);
    document.head.appendChild(script);
  }

  if (FILTERS) {
    FILTERS.addEventListener('click', e => {
      const btn = e.target.closest('button[data-category]');
      if (!btn) return;
      setCategory(btn.dataset.category || 'all');
      render();
      // Keep the address on the view shown: a reload reopens the same
      // filter, and a menu link to another section is then a change.
      history.replaceState(null, '', hashForCategory(activeCategory));
    });
  }

  // === Section anchors ===
  // The menu and the sitemap link to #showcase and to one section per
  // category (#templates-section, ...). A category section exists only
  // while its filter renders it, so each of these anchors selects its
  // filter before the page moves to the gallery.
  const GALLERY_HASH = '#showcase';

  function categoryForHash(hash) {
    if (!manifest || !hash) return null;
    if (hash === GALLERY_HASH) return 'all';
    const category = (manifest.categories || [])
      .find(c => hash === '#' + c.id + '-section');
    return category ? category.id : null;
  }

  function hashForCategory(categoryId) {
    return categoryId === 'all' ? GALLERY_HASH : '#' + categoryId + '-section';
  }

  function setCategory(categoryId) {
    activeCategory = categoryId;
    if (!FILTERS) return;
    FILTERS.querySelectorAll('.filter-pill').forEach(b => {
      b.classList.toggle('is-active', (b.dataset.category || 'all') === categoryId);
    });
  }

  // Shows a category's view. A view already shown is not rebuilt, so an
  // expanded group stays open, and the search is kept unless it hides the
  // very section the anchor names.
  function showCategory(categoryId) {
    if (categoryId !== activeCategory) {
      setCategory(categoryId);
      render();
    }
    if (categoryId !== 'all' && activeQuery && !document.getElementById(categoryId + '-section')) {
      if (SEARCH) SEARCH.value = '';
      activeQuery = '';
      render();
    }
  }

  // Whether this load is a reload or a history traversal, where the browser
  // puts the reader back at the position they left.
  function isRestoringScroll() {
    const entry = performance.getEntriesByType ? performance.getEntriesByType('navigation')[0] : null;
    return !!entry && (entry.type === 'reload' || entry.type === 'back_forward');
  }

  // Aligns the gallery heading below the sticky header, which on a
  // narrow screen is taller than the section's top padding. `jump`
  // bypasses the page's smooth scrolling, for a page opened at an anchor.
  function scrollToGallery(jump) {
    const gallery = document.getElementById('showcase');
    if (!gallery) return;
    const header = document.querySelector('.site-header');
    const headerHeight = header ? header.getBoundingClientRect().height : 0;
    const heading = gallery.querySelector('.section-heading') || gallery;
    const top = Math.max(0, heading.getBoundingClientRect().top + window.scrollY - headerHeight - 16);
    const root = document.documentElement;
    const inlineBehavior = root.style.scrollBehavior;
    if (jump) root.style.scrollBehavior = 'auto';
    window.scrollTo(0, top);
    if (jump) root.style.scrollBehavior = inlineBehavior;
  }

  // A link the browser follows moves keyboard focus to its target; one
  // handled here has to do the same, or Tab takes the reader back to the menu.
  function focusGallery() {
    const title = document.getElementById('showcase-title');
    if (!title) return;
    title.setAttribute('tabindex', '-1');
    title.focus({ preventScroll: true });
  }

  // === Document viewer ===
  // Cards, featured tiles and family tiles open the viewer (gallery-viewer.js).
  // Its address, #/<category>/<group>/<id>, reopens it on a reload, from a
  // shared link, and on Back and Forward.
  function startViewer() {
    catalogue = buildCatalogue();
    if (Gallery && VIEWER_DIALOG && typeof VIEWER_DIALOG.showModal === 'function') {
      viewer = Gallery.createViewer({ dialog: VIEWER_DIALOG, catalogue, onClose: onViewerClosed });
    }
  }

  function viewerRoute(hash) {
    return Gallery ? Gallery.parseRoute(hash) : null;
  }

  // Opens a route in the viewer. An address that names no family is put back
  // to the gallery rather than left in the address bar.
  function openRoute(route, historyMode, opener) {
    if (viewer && viewer.open(route, { history: historyMode, opener })) return true;
    if (viewerRoute(location.hash)) history.replaceState(null, '', GALLERY_HASH);
    // The address names no document any more, so the viewer must not stay open over the
    // gallery still showing the one before it.
    if (viewer && viewer.isOpen()) viewer.close({ byHistory: true });
    return false;
  }

  // The view of the manifest the viewer navigates: every family with the ids
  // it holds, and each id's example with the family it lives in.
  function buildCatalogue() {
    const index = buildIndex();
    const categories = (manifest.categories || []).map(category => ({
      id: category.id,
      label: category.label,
      groups: (category.groups || []).map(group => ({
        id: group.id,
        label: group.label,
        ids: (group.examples || []).filter(ex => ex && ex.id).map(ex => ex.id)
      }))
    }));
    return { categories, get: id => index.get(id) };
  }

  // Closing returns the address to the gallery (Back when the viewer added the
  // entry, a replacement otherwise), and focus to what opened the viewer, or to
  // the card of the document last shown.
  function onViewerClosed(closed) {
    if (!closed.byHistory) {
      if (history.state && history.state.galleryViewer) {
        history.back();
      } else {
        history.replaceState(null, '', hashForCategory(activeCategory));
      }
    }
    const opener = closed.opener && document.contains(closed.opener) ? closed.opener : null;
    const shownId = closed.view && closed.view.id;
    const card = !opener && shownId
      ? CONTENT.querySelector('[data-action="view"][data-id="' + cssEscape(shownId) + '"]')
      : null;
    if (opener) {
      opener.focus({ preventScroll: true });
    } else if (card) {
      card.scrollIntoView({ block: 'center' });
      card.focus({ preventScroll: true });
    } else {
      focusGallery();
    }
  }

  // The preview's own pixel size, from the catalogue. The card's box is a fixed height
  // either way, so this is not what keeps the grid still: it lets the image reserve its slot
  // inside that box at the right shape rather than appear out of nothing — and no single
  // size can stand in for all of them, since 26 of the previews are not A4.
  function sizeAttrs(example) {
    return example.previewWidth && example.previewHeight
      ? ' width="' + example.previewWidth + '" height="' + example.previewHeight + '"'
      : '';
  }

  function cssEscape(value) {
    return window.CSS && CSS.escape ? CSS.escape(value) : String(value).replace(/["\\]/g, '\\$&');
  }

  document.addEventListener('click', e => {
    if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
    const link = e.target.closest('a[href^="#"]');
    if (!link) return;
    const hash = link.getAttribute('href');
    const route = viewer ? viewerRoute(hash) : null;
    if (route) {
      e.preventDefault();
      openRoute(route, 'push', link);
      return;
    }
    const categoryId = categoryForHash(hash);
    if (!categoryId) return;
    e.preventDefault();
    if (location.hash !== hash) history.pushState(null, '', hash);
    showCategory(categoryId);
    scrollToGallery(false);
    focusGallery();
  });

  // Back / Forward, or an anchor typed into the address bar. A viewer address
  // opens the viewer, and leaving one closes it. An entry with no anchor is the
  // page as it was before a gallery link was followed: it shows the whole
  // gallery, at the position the browser restores.
  window.addEventListener('hashchange', () => {
    if (!manifest) return;
    const route = viewerRoute(location.hash);
    if (route) {
      openRoute(route, 'none', document.activeElement);
      return;
    }
    if (viewer && viewer.isOpen()) viewer.close({ byHistory: true });
    const categoryId = location.hash ? categoryForHash(location.hash) : 'all';
    if (!categoryId || categoryId === activeCategory) return;
    showCategory(categoryId);
    if (location.hash) scrollToGallery(false);
  });

  if (SEARCH) {
    SEARCH.addEventListener('input', e => {
      activeQuery = (e.target.value || '').trim().toLowerCase();
      render();
    });
  }

  // Build an { id -> {example, categoryId} } lookup so highlight
  // tiles can resolve their data without rerunning the search loop.
  function buildIndex() {
    const idx = new Map();
    for (const category of manifest.categories || []) {
      for (const group of category.groups || []) {
        for (const example of group.examples || []) {
          if (example && example.id) {
            idx.set(example.id, { example, categoryId: category.id, groupId: group.id });
          }
        }
      }
    }
    return idx;
  }

  function render() {
    if (!manifest) return;
    const fragments = [];
    let total = 0;
    const index = buildIndex();

    // Families: one tile per family of the category in view, each opening the
    // viewer on it. Hidden during a search, like the featured strip.
    if (viewer && !activeQuery) {
      const familiesOf = (manifest.categories || [])
        .find(c => c.id === (activeCategory === 'all' ? 'templates' : activeCategory));
      if (familiesOf && (familiesOf.groups || []).length > 1) {
        fragments.push(renderFamilies(familiesOf));
      }
    }

    // Highlights strip: rendered when no search query is active and
    // the user hasn't drilled into a single category. Once they
    // start filtering, hide the strip — they're past the wow stage
    // and into "find the specific one" territory.
    const showHighlights =
        !activeQuery && activeCategory === 'all';
    if (showHighlights) {
      const tiles = [];
      for (const id of HIGHLIGHT_IDS) {
        const hit = index.get(id);
        if (hit) tiles.push(renderHighlight(hit.example, hit.categoryId));
      }
      if (tiles.length > 0) {
        fragments.push(renderHighlightsStrip(tiles));
      }
    }

    for (const category of manifest.categories || []) {
      if (activeCategory !== 'all' && activeCategory !== category.id) {
        continue;
      }
      const groupBlocks = [];
      let categoryCount = 0;
      for (const group of category.groups || []) {
        const matching = (group.examples || []).filter(matchesQuery);
        if (matching.length === 0) continue;
        categoryCount += matching.length;
        groupBlocks.push(renderGroup(group, matching));
      }
      if (categoryCount === 0) continue;
      total += categoryCount;
      fragments.push(renderCategory(category, groupBlocks, categoryCount));
    }

    if (total === 0) {
      CONTENT.innerHTML =
        '<p class="showcase-empty">No examples match the current filter or search query.</p>';
      return;
    }
    CONTENT.innerHTML = fragments.join('\n');
    afterRender();
  }

  // Post-render hook: wire scroll arrows on the highlights strip
  // (only meaningful once the actual DOM exists and we can measure
  // overflow). Runs after every render() so it picks up the strip
  // appearing/disappearing on filter changes.
  function afterRender() {
    initHighlightsArrows();
  }

  function initHighlightsArrows() {
    const strip = CONTENT.querySelector('.highlights-strip');
    if (!strip) return;
    // Skip if we already attached arrows on a previous render.
    if (strip.dataset.arrowsReady === '1') return;
    strip.dataset.arrowsReady = '1';

    const wrapper = strip.parentElement;
    if (!wrapper) return;
    wrapper.classList.add('has-strip-arrows');

    const left = document.createElement('button');
    left.type = 'button';
    left.className = 'strip-arrow strip-arrow-left';
    left.setAttribute('aria-label', 'Scroll featured examples left');
    left.innerHTML = '&#x2039;';

    const right = document.createElement('button');
    right.type = 'button';
    right.className = 'strip-arrow strip-arrow-right';
    right.setAttribute('aria-label', 'Scroll featured examples right');
    right.innerHTML = '&#x203A;';

    const tileStep = () => {
      const tile = strip.querySelector('.highlight-tile');
      if (!tile) return 320;
      const styles = window.getComputedStyle(strip);
      const gap = parseFloat(styles.columnGap || styles.gap || '0') || 0;
      return tile.getBoundingClientRect().width + gap;
    };

    left.addEventListener('click', () => {
      strip.scrollBy({ left: -tileStep(), behavior: 'smooth' });
    });
    right.addEventListener('click', () => {
      strip.scrollBy({ left: tileStep(), behavior: 'smooth' });
    });

    const updateArrowState = () => {
      const max = strip.scrollWidth - strip.clientWidth;
      const overflow = max > 4;
      wrapper.classList.toggle('strip-overflow', overflow);
      left.disabled = strip.scrollLeft <= 2;
      right.disabled = strip.scrollLeft >= max - 2;
    };

    strip.addEventListener('scroll', updateArrowState, { passive: true });
    window.addEventListener('resize', updateArrowState, { passive: true });

    wrapper.appendChild(left);
    wrapper.appendChild(right);
    // Initial state once layout settles.
    requestAnimationFrame(updateArrowState);
  }

  // A family tile: a featured document of the family as its cover when there
  // is one, the family's name, and its count from the manifest.
  function renderFamilies(category) {
    const heading = category.id === 'templates'
      ? 'Browse templates by family'
      : 'Browse ' + String(category.label || category.id).toLowerCase() + ' by topic';
    const tiles = (category.groups || [])
      .filter(group => (group.examples || []).length > 0)
      .map(group => {
        const examples = group.examples;
        const cover = examples.find(ex => HIGHLIGHT_IDS.includes(ex.id)) || examples[0];
        const count = examples.length;
        const href = Gallery.formatRoute({ category: category.id, group: group.id });
        return [
          '<a class="family-tile" href="' + escAttr(href) + '">',
          '  <span class="family-cover">',
          // A family tile is a small box: it reads the strip-sized image, not the whole page.
          cover.thumbnail
            ? '    <img loading="lazy" decoding="async" src="' + escAttr(cover.thumbnail) + '" alt="">'
            : '',
          '  </span>',
          '  <span class="family-name">' + escHtml(group.label || group.id) + '</span>',
          '  <span class="family-count">' + count + ' document' + (count === 1 ? '' : 's') + '</span>',
          '</a>'
        ].join('\n');
      });
    return [
      '<section class="showcase-families" aria-labelledby="families-heading">',
      '  <header class="highlights-heading">',
      '    <h3 id="families-heading">' + escHtml(heading) + '</h3>',
      '    <p class="highlights-sub">Open a family to page through its documents one at a time.</p>',
      '  </header>',
      '  <div class="families-grid">',
      tiles.join('\n'),
      '  </div>',
      '</section>'
    ].join('\n');
  }

  function renderHighlightsStrip(tiles) {
    return [
      '<section class="showcase-highlights" aria-labelledby="highlights-heading">',
      '  <header class="highlights-heading">',
      '    <h3 id="highlights-heading">Featured</h3>',
      '    <p class="highlights-sub">A spread across templates, features, and flagships &mdash; open any tile to page through its family.</p>',
      '  </header>',
      '  <div class="highlights-strip" role="list">',
      tiles.join('\n'),
      '  </div>',
      '</section>'
    ].join('\n');
  }

  function renderHighlight(ex, categoryId) {
    const screenshot = ex.screenshot || '';
    const pdf = ex.pdf || '';
    const badge = CATEGORY_BADGE[categoryId] || '';
    return [
      '<article class="highlight-tile" data-id="' + escAttr(ex.id || '') + '" role="listitem">',
      '  <button type="button" class="highlight-preview"',
      '          data-action="view"',
      '          data-id="' + escAttr(ex.id || '') + '"',
      '          data-pdf="' + escAttr(pdf) + '"',
      '          aria-label="Open ' + escAttr(ex.title || ex.id || '') + ' in the viewer">',
      screenshot
        ? '    <img loading="lazy" decoding="async"' + sizeAttrs(ex) + ' src="' + escAttr(screenshot) + '" alt="' + escAttr(ex.title || '') + ' preview">'
        : '    <div class="example-preview-fallback">PDF</div>',
      badge ? '    <span class="highlight-badge">' + escHtml(badge) + '</span>' : '',
      '  </button>',
      '  <div class="highlight-meta">',
      '    <h5 class="highlight-title">' + escHtml(ex.title || ex.id || '') + '</h5>',
      '    <p class="highlight-desc">' + escHtml(ex.description || '') + '</p>',
      '  </div>',
      '</article>'
    ].join('\n');
  }

  function matchesQuery(example) {
    if (!activeQuery) return true;
    const haystack = [
      example.id || '',
      example.title || '',
      example.description || '',
      (example.tags || []).join(' '),
      hasAtsBadge(example) ? 'ats-friendly' : ''
    ].join(' ').toLowerCase();
    return haystack.includes(activeQuery);
  }

  // A card shows the chip only when the manifest marks the badge AND its
  // status is one that earns it.
  function hasAtsBadge(example) {
    const ats = example.ats;
    return !!ats && ats.badge === true && ATS_BADGE_STATUSES.has(ats.status);
  }

  // The chip's tooltip: the conservative claim, a compatible preset's known
  // limitation, and when and with what the sample was checked.
  function atsBadgeTitle(ats) {
    const parts = [ATS_BADGE_CLAIM];
    const limitations = ats.knownLimitations || [];
    if (limitations.length) {
      parts.push('Known parser limitation: ' + limitations.join(' '));
    }
    if (ats.lastValidated) {
      const tested = ats.tested || [];
      parts.push('Checked on ' + ats.lastValidated + ' against the sample shown'
        + (tested.length ? ', with ' + tested.join(', ') : '') + '.');
    }
    return parts.join(' ');
  }

  function renderCategory(category, groupBlocks, count) {
    const sectionId = category.id + '-section';
    return [
      '<section class="showcase-category" id="' + escAttr(sectionId) + '">',
      '  <header class="category-heading">',
      '    <h3>' + escHtml(category.label) + '</h3>',
      '    <span class="category-count">' + count + ' example' + (count === 1 ? '' : 's') + '</span>',
      '  </header>',
      groupBlocks.join('\n'),
      '</section>'
    ].join('\n');
  }

  function renderGroup(group, examples) {
    const collapsible = COLLAPSE_GROUPS.has(group.id) && examples.length > COLLAPSED_VISIBLE;
    const groupClass = collapsible
      ? 'showcase-group is-collapsible is-collapsed'
      : 'showcase-group';
    const dataAttr = collapsible
      ? ' data-visible="' + COLLAPSED_VISIBLE + '"'
      : '';
    const toggle = collapsible
      ? '    <button type="button" class="group-toggle" data-action="toggle-group">'
        + 'Show all <span class="group-toggle-count">' + examples.length + '</span> &darr;'
        + '</button>'
      : '';
    return [
      '  <section class="' + groupClass + '"' + dataAttr + '>',
      '    <header class="group-heading"><h4>' + escHtml(group.label) + '</h4>',
      '    <span class="group-count">' + examples.length + '</span></header>',
      '    <div class="examples-grid">',
      examples.map(renderCard).join('\n'),
      '    </div>',
      toggle,
      '  </section>'
    ].join('\n');
  }

  function renderCard(ex) {
    const tags = (ex.tags || [])
      .map(t => '<span class="tag">' + escHtml(t) + '</span>').join('');
    // The chip links to the documented claim, so a keyboard or touch visitor
    // reaches the caveats a pointer reads in the tooltip. The claim also rides
    // in visually hidden text for a screen reader.
    const atsTitle = hasAtsBadge(ex) ? atsBadgeTitle(ex.ats) : '';
    const atsNote = '<span class="ats-badge-note">. ' + escHtml(atsTitle) + '</span>';
    const atsBadge = !atsTitle
      ? ''
      : ex.ats.details
        ? '<a class="ats-badge" href="' + escAttr(ex.ats.details) + '" target="_blank" rel="noopener"'
          + ' title="' + escAttr(atsTitle) + '">ATS-friendly' + atsNote + '</a>'
        : '<span class="ats-badge" title="' + escAttr(atsTitle) + '">ATS-friendly' + atsNote + '</span>';
    const screenshot = ex.screenshot || '';
    const pdf = ex.pdf || '';
    const pptx = ex.pptx || '';
    const code = ex.code || '#';
    const altText = buildAlt(ex);
    return [
      '<article class="example-card" data-id="' + escAttr(ex.id || '') + '">',
      '  <button type="button" class="example-preview"',
      '          data-action="view"',
      '          data-id="' + escAttr(ex.id || '') + '"',
      '          data-pdf="' + escAttr(pdf) + '"',
      '          aria-label="Open ' + escAttr(ex.title || ex.id || '') + ' in the viewer">',
      screenshot
        ? '    <img loading="lazy" decoding="async"' + sizeAttrs(ex) + ' src="' + escAttr(screenshot) + '" alt="' + escAttr(altText) + '">'
        : '    <div class="example-preview-fallback">PDF</div>',
      '    <span class="example-view-hint">View</span>',
      '  </button>',
      '  <div class="example-body">',
      '    <h5 class="example-title">' + escHtml(ex.title || ex.id || '') + '</h5>',
      '    <p class="example-desc">' + escHtml(ex.description || '') + '</p>',
      (atsBadge || tags) ? '    <div class="example-tags">' + atsBadge + tags + '</div>' : '',
      '    <div class="example-actions">',
      '      <a class="example-action" href="' + escAttr(pdf) + '" target="_blank" rel="noopener" aria-label="Open PDF">View PDF</a>',
      // A twin flagship also ships the deck the same session emitted. Only the
      // examples that actually rendered one carry `pptx`, so the link is omitted
      // rather than dead for every PDF-only card.
      pptx
        ? '      <a class="example-action example-action-ghost" href="' + escAttr(pptx) + '" download aria-label="Download PowerPoint deck">Get PPTX</a>'
        : '',
      '      <a class="example-action example-action-ghost" href="' + escAttr(code) + '" target="_blank" rel="noopener" aria-label="Open source on GitHub">View Code</a>',
      '    </div>',
      '  </div>',
      '</article>'
    ].join('\n');
  }

  // Build a descriptive img alt: prefer "{title} — {first sentence
  // of description}" so screen-reader users + image-search crawlers
  // get more than just "X preview".
  function buildAlt(ex) {
    const title = (ex.title || ex.id || '').trim();
    let desc = (ex.description || '').trim();
    if (desc) {
      // Strip trailing period, take only first sentence, cap length.
      const sentenceEnd = desc.search(/[.!?](\s|$)/);
      if (sentenceEnd > 0) desc = desc.slice(0, sentenceEnd);
      if (desc.length > 110) desc = desc.slice(0, 107).trim() + '...';
      return title + ' — ' + desc;
    }
    return title + ' preview';
  }

  document.addEventListener('click', e => {
    // Group expand/collapse (oversized groups like Cover Letter).
    const toggleBtn = e.target.closest('[data-action="toggle-group"]');
    if (toggleBtn) {
      const group = toggleBtn.closest('.showcase-group');
      if (group) {
        const collapsed = group.classList.toggle('is-collapsed');
        const total = group.querySelectorAll('.example-card').length;
        toggleBtn.innerHTML = collapsed
          ? 'Show all <span class="group-toggle-count">' + total + '</span> &darr;'
          : 'Show fewer &uarr;';
      }
      return;
    }

    // A card or featured tile opens its document in the viewer; without the
    // viewer it opens the PDF.
    const trigger = e.target.closest('[data-action="view"]');
    if (!trigger) return;
    e.preventDefault();
    const hit = catalogue && catalogue.get(trigger.dataset.id);
    if (hit && viewer) {
      openRoute({ category: hit.categoryId, group: hit.groupId, id: hit.example.id }, 'push', trigger);
    } else if (trigger.dataset.pdf) {
      window.open(trigger.dataset.pdf, '_blank', 'noopener');
    }
  });

  function escHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  function escAttr(s) {
    return escHtml(s);
  }
})();
